package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import controller.IStockMarketController;

/**
 *
 * @author ojaspatwardhan
 */
public class ApplyStrategyPanel extends javax.swing.JPanel {

    private IStockMarketController stockMarketController;

    /**
     * Creates new form ApplyStrategyPanel
     */
    public ApplyStrategyPanel(IStockMarketController stockMarketController) {
        initComponents();
        this.stockMarketController = stockMarketController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portfolioNumberLbl = new javax.swing.JLabel();
        portfolioNumberTextField = new javax.swing.JTextField();
        weightsLbl = new javax.swing.JLabel();
        weightsComoboBox = new javax.swing.JComboBox<>();
        weightsTextField = new javax.swing.JTextField();
        updateWeightBtn = new javax.swing.JButton();
        executeCustomWeightsBtn = new javax.swing.JButton();
        executeEqualWeightsBtn = new javax.swing.JButton();

        portfolioNumberLbl.setText("Enter portfolio number.");

        portfolioNumberTextField.setText("Enter number here.");

        weightsLbl.setText("Select Weights.");

        weightsComoboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        weightsTextField.setText("Enter weight");

        updateWeightBtn.setText("Update weight");

        executeCustomWeightsBtn.setText("Execute using custom weights");

        executeEqualWeightsBtn.setText("Execute using equal weights");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(portfolioNumberTextField)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portfolioNumberLbl)
                    .addComponent(weightsLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weightsComoboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateWeightBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(executeCustomWeightsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeEqualWeightsBtn)))
                .addGap(0, 338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portfolioNumberLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portfolioNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightsComoboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateWeightBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeCustomWeightsBtn)
                    .addComponent(executeEqualWeightsBtn))
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeCustomWeightsBtn;
    private javax.swing.JButton executeEqualWeightsBtn;
    private javax.swing.JLabel portfolioNumberLbl;
    private javax.swing.JTextField portfolioNumberTextField;
    private javax.swing.JButton updateWeightBtn;
    private javax.swing.JComboBox<String> weightsComoboBox;
    private javax.swing.JLabel weightsLbl;
    private javax.swing.JTextField weightsTextField;
    // End of variables declaration//GEN-END:variables
}
