package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import controller.IStockMarketController;

/**
 * The class Buy stock panel which has the components of buy stock.
 *
 * @author ojaspatwardhan
 */
public class BuyStockPanel extends javax.swing.JPanel {

  private IStockMarketController stockMarketController;

  /**
   * Creates new form buyStockPanel
   *
   * @param stockMarketController the stock market controller
   */
  public BuyStockPanel(IStockMarketController stockMarketController) {
    this.stockMarketController = stockMarketController;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tickerLabel = new javax.swing.JLabel();
    tickerTextField = new javax.swing.JTextField();
    resultLabel = new javax.swing.JLabel();
    numberOfStocksLabel = new javax.swing.JLabel();
    numberOfStockTextField = new javax.swing.JTextField();
    dateLabel = new javax.swing.JLabel();
    dateField = new javax.swing.JTextField();
    portfolioNumberLabel = new javax.swing.JLabel();
    portfolioNumberField = new javax.swing.JTextField();
    commissionAmountLabel = new javax.swing.JLabel();
    commissionAmountField = new javax.swing.JTextField();
    buyStockBtn = new javax.swing.JButton();

    tickerLabel.setText("Please enter the ticker.");

    dateLabel.setText("Please enter the date (yyyy-mm-dd).");

    numberOfStocksLabel.setText("Please enter the number of stocks.");

    portfolioNumberLabel.setText("Please enter the portfolio number.");

    commissionAmountLabel.setText("Please enter the commission amount (in %).");

    resultLabel.setText("result label");

    buyStockBtn.setText("Buy");

    buyStockBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        buyStock();
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout
                                    .Alignment.LEADING)
                                    .addComponent(tickerLabel,
                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tickerTextField)
                                    .addComponent(numberOfStockTextField)
                                    .addComponent(dateField)
                                    .addComponent(portfolioNumberField)
                                    .addComponent(commissionAmountField)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dateLabel)
                                                    .addComponent(portfolioNumberLabel)
                                                    .addComponent(commissionAmountLabel)
                                                    .addComponent(resultLabel)
                                                    .addComponent(numberOfStocksLabel))
                                            .addGap(0, 115, Short.MAX_VALUE)))
                            .addContainerGap())
                    .addComponent(buyStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tickerLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tickerTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numberOfStocksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numberOfStockTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(portfolioNumberLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(portfolioNumberField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(commissionAmountLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(commissionAmountField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resultLabel)
                            .addComponent(buyStockBtn)
                            .addContainerGap(43, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Private buyStock method which buys stocks.
   */
  private void buyStock() {
    String pNumber = portfolioNumberField.getText();
    String date = dateField.getText();
    String ticker = tickerTextField.getText();
    String commissionText = commissionAmountField.getText();
    String nOfS = numberOfStockTextField.getText();
    try {
      int pn = Integer.parseInt(pNumber);
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      Date date1 = dateFormat.parse(date);
      int commission = Integer.parseInt(commissionText);
      double numberOfStock = Double.parseDouble(nOfS);
      if (pn < 0 || commission < 0 || numberOfStock < 0) {
        resultLabel.setText("Enter positive number");
      } else if (date1.after(new Date())) {
        resultLabel.setText("Future dates are not valid.");
      } else {
        String response = stockMarketController.buyStock(ticker, numberOfStock, date, pn,
                commission);
        if (response.equals("pass")) {
          resultLabel.setText("Stock bought successfully.");
        } else {
          resultLabel.setText(response);
        }
      }
    } catch (NumberFormatException ne) {
      resultLabel.setText("Please enter a number.");
    } catch (ParseException e) {
      resultLabel.setText("Enter date in format (yyyy-MM-dd).");
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buyStockBtn;
  private javax.swing.JTextField commissionAmountField;
  private javax.swing.JLabel commissionAmountLabel;
  private javax.swing.JTextField dateField;
  private javax.swing.JLabel dateLabel;
  private javax.swing.JTextField portfolioNumberField;
  private javax.swing.JLabel portfolioNumberLabel;
  private javax.swing.JLabel tickerLabel;
  private javax.swing.JTextField tickerTextField;
  private javax.swing.JLabel resultLabel;
  private javax.swing.JLabel numberOfStocksLabel;
  private javax.swing.JTextField numberOfStockTextField;
  // End of variables declaration//GEN-END:variables
}
