package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import controller.IStockMarketController;

/**
 * The class Cost basis evaluation panel.
 *
 * @author ojaspatwardhan
 */
public class CostBasisEvaluationPanel extends javax.swing.JPanel {

  private IStockMarketController stockMarketController;

  /**
   * Creates new form CostBasisEvaluationPanel.
   *
   * @param stockMarketController the stock market controller
   */
  public CostBasisEvaluationPanel(IStockMarketController stockMarketController) {
    initComponents();
    this.stockMarketController = stockMarketController;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JLabel costBEvaluationPortfolioNumber = new javax.swing.JLabel();
    costBEPortfolioNumberTF = new javax.swing.JTextField();
    javax.swing.JLabel costBasisEvaluationDateLabel = new javax.swing.JLabel();
    costBasisEvaluationDateField = new javax.swing.JTextField();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton costBasisEvaluationBtn = new javax.swing.JButton();
    jTextArea2 = new javax.swing.JTextArea();
    jTextArea2.setEditable(false);
    costBEvaluationPortfolioNumber.setText("Please enter the portfolio number.");

    costBEPortfolioNumberTF.setText("");

    costBasisEvaluationDateLabel.setText("Please enter the date (yyyy-mm-dd).");

    costBasisEvaluationDateField.setText("");

    costBasisEvaluationBtn.setText("Calculate");

    costBasisEvaluationBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        costBasisAndEvaluate();
      }
    });

    jTextArea2.setColumns(10);
    jTextArea2.setRows(2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                            layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(
                                            javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextArea2,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    661, Short.MAX_VALUE)
                                            .addComponent(costBasisEvaluationBtn,
                                                    javax.swing.GroupLayout.Alignment.LEADING,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                    javax.swing.GroupLayout.DEFAULT_SIZE, 
                                                    Short.MAX_VALUE)
                                            .addComponent(costBEPortfolioNumberTF,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(costBasisEvaluationDateField,
                                                    javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                    layout.createParallelGroup(javax.swing.
                                                            GroupLayout.Alignment.LEADING)
                                                            .addComponent(
                                                                    costBEvaluationPortfolioNumber)
                                                            .addComponent(
                                                                    costBasisEvaluationDateLabel).
                                                            addGroup(layout.createSequentialGroup())
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                    )
                                    .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(costBEvaluationPortfolioNumber)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costBEPortfolioNumberTF,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costBasisEvaluationDateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costBasisEvaluationDateField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(costBasisEvaluationBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextArea2,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, 299,
                                    Short.MAX_VALUE)
                            .addContainerGap())
    );
  } // </editor-fold>//GEN-END:initComponents

  /**
   * Private helper method to calculate cost basis and evaluation of a portfolio.
   */
  private void costBasisAndEvaluate() {
    String pNumber = costBEPortfolioNumberTF.getText();
    String date = costBasisEvaluationDateField.getText();
    try {
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      int profileNumber = Integer.parseInt(pNumber);
      Date date1 = dateFormat.parse(date);
      if (date1.after(new Date())) {
        this.jTextArea2.setText("Future dates are not valid");
        return;
      } else if (profileNumber < 0) {
        this.jTextArea2.setText("Portfolio number cannot be negative");
        return;
      }
      String response = this.stockMarketController.costBasisAndEvaluation(profileNumber, date);
      this.jTextArea2.setText(response);
    } catch (NumberFormatException ne) {
      this.jTextArea2.setText("Enter a valid number.");
    } catch (ParseException e) {
      this.jTextArea2.setText("Enter valid date of format (yyyy-MM-dd).");
    } catch (IllegalArgumentException e) {
      this.jTextArea2.setText(e.getMessage());
    }
  }

  private javax.swing.JTextField costBasisEvaluationDateField;
  private javax.swing.JTextField costBEPortfolioNumberTF;
  private javax.swing.JTextArea jTextArea2;
  // End of variables declaration//GEN-END:variables
}
