package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaspatwardhan
 */
public class CostBasisEvaluationPanel extends javax.swing.JPanel {

    /**
     * Creates new form CostBasisEvaluationPanel
     */
    public CostBasisEvaluationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        costBasisEvaluationPortfolioNumber = new javax.swing.JLabel();
        costBasisEvaluationPortfolioNumberTextField = new javax.swing.JTextField();
        costBasisEvaluationDateLabel = new javax.swing.JLabel();
        costBasisEvaluationDateField = new javax.swing.JTextField();
        costBasisEvaluationBtn = new javax.swing.JButton();
        costBasisEvaluationTextArea = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        costBasisEvaluationPortfolioNumber.setText("Please enter the portfolio number.");

        costBasisEvaluationPortfolioNumberTextField.setText("Enter portfolio number here.");

        costBasisEvaluationDateLabel.setText("Please enter the date (yyyy-mm-dd).");

        costBasisEvaluationDateField.setText("Enter the date here.");

        costBasisEvaluationBtn.setText("Calculate");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        costBasisEvaluationTextArea.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costBasisEvaluationTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addComponent(costBasisEvaluationBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costBasisEvaluationPortfolioNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costBasisEvaluationDateField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costBasisEvaluationPortfolioNumber)
                            .addComponent(costBasisEvaluationDateLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(costBasisEvaluationPortfolioNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costBasisEvaluationPortfolioNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costBasisEvaluationDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costBasisEvaluationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costBasisEvaluationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costBasisEvaluationTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton costBasisEvaluationBtn;
    private javax.swing.JTextField costBasisEvaluationDateField;
    private javax.swing.JLabel costBasisEvaluationDateLabel;
    private javax.swing.JLabel costBasisEvaluationPortfolioNumber;
    private javax.swing.JTextField costBasisEvaluationPortfolioNumberTextField;
    private javax.swing.JScrollPane costBasisEvaluationTextArea;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
