package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.LayoutStyle.ComponentPlacement;

import controller.IStockMarketController;
import model.Stock;

import static javax.swing.GroupLayout.PREFERRED_SIZE;
import static javax.swing.GroupLayout.DEFAULT_SIZE;
import static javax.swing.GroupLayout.Alignment;
import static javax.swing.GroupLayout.Alignment.LEADING;

/**
 * The class Create strategy panel.
 *
 * @author ojaspatwardhan
 */
public class CreateStrategyPanel extends javax.swing.JPanel {

  private IStockMarketController stockMarketController;
  private List<Stock> stockList;
  private Map<String, Integer> weights;

  /**
   * Creates new form CreateStrategypanel.
   *
   * @param stockMarketController the stock market controller
   */
  public CreateStrategyPanel(IStockMarketController stockMarketController) {
    initComponents();
    this.stockMarketController = stockMarketController;
    this.strategyEndDateLbl.setVisible(false);
    this.strategyEndDateField.setVisible(false);
    this.stockList = new ArrayList<>();
    this.weights = new HashMap<>();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JLabel strategyPortfolioNumberLabel = new javax.swing.JLabel();
    strategyPortfolioNumberField = new javax.swing.JTextField();
    javax.swing.JLabel startDateLabel = new javax.swing.JLabel();
    strategyStartDateField = new javax.swing.JTextField();
    javax.swing.JLabel strategyEndDateLabel = new javax.swing.JLabel();
    strategyEndDateComboBox = new javax.swing.JComboBox<>();
    strategyEndDateLbl = new javax.swing.JLabel();
    strategyEndDateField = new javax.swing.JTextField();
    javax.swing.JLabel strategyFrequencyLabel = new javax.swing.JLabel();
    strategyFrequencyField = new javax.swing.JTextField();
    javax.swing.JLabel strategyAmountLabel = new javax.swing.JLabel();
    strategyAmountField = new javax.swing.JTextField();
    javax.swing.JLabel weightsLabel = new javax.swing.JLabel();
    tickerComboBox = new javax.swing.JComboBox<>();
    weightsTextField = new javax.swing.JTextField();
    javax.swing.JButton updateWeightsBtn = new javax.swing.JButton();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton customWeightsBtn = new javax.swing.JButton();
    javax.swing.JButton equalWeightsBtn = new javax.swing.JButton();
    javax.swing.JButton saveStrategyBtn = new javax.swing.JButton();
    resultLbl = new javax.swing.JLabel();
    strategyNumberField = new javax.swing.JTextField();
    javax.swing.JLabel strategyNumberLabel = new javax.swing.JLabel();

    strategyStartDateField.addFocusListener(new FocusListener() {
      @Override
      public void focusGained(FocusEvent focusEvent) {
        //do nothing.
      }

      @Override
      public void focusLost(FocusEvent focusEvent) {
        getStocks(focusEvent);
      }
    });

    strategyPortfolioNumberLabel.setText("Please enter the portfolio number.");

    strategyNumberLabel.setText("Enter strategy number.");

    startDateLabel.setText("Please enter the start date (yyyy-mm-dd).");

    strategyEndDateLabel.setText("Would you like to enter the end date.");

    strategyEndDateComboBox.setModel(new
            javax.swing.DefaultComboBoxModel<>(new String[]{"No", "Yes"}));

    strategyEndDateLbl.setText("Please enter the end date.");

    strategyFrequencyLabel.setText("Please enter the frequency (in days).");

    strategyAmountLabel.setText("Please enter the amount you would like to invest ($).");

    weightsLabel.setText("Select weights");

    tickerComboBox.setModel(
            new javax.swing.DefaultComboBoxModel<>(
                    new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

    weightsTextField.setText("Enter weight");

    updateWeightsBtn.setText("Update weight");

    customWeightsBtn.setText("Execute using custom weights");

    equalWeightsBtn.setText("Execute using equal weights");

    saveStrategyBtn.setText("Save Strategy");

    strategyEndDateComboBox.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        if (strategyEndDateComboBox.getSelectedIndex() == 1) {
          strategyEndDateField.setVisible(true);
          strategyEndDateLbl.setVisible(true);
        } else if (strategyEndDateComboBox.getSelectedIndex() == 0) {
          strategyEndDateField.setVisible(false);
          strategyEndDateLbl.setVisible(false);
        }
      }
    });

    updateWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        updateWeights(actionEvent);
      }
    });

    tickerComboBox.addFocusListener(new FocusListener() {
      @Override
      public void focusGained(FocusEvent focusEvent) {
        resultLbl.setText("");
      }

      @Override
      public void focusLost(FocusEvent focusEvent) {
        //do nothing.
      }
    });

    customWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        executeStrategy(actionEvent,
                true);
      }
    });

    equalWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        executeStrategy(actionEvent,
                false);
      }
    });

    saveStrategyBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        saveStrategy(actionEvent);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(LEADING)
                    .addComponent(strategyAmountField)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.
                                    createParallelGroup(LEADING)
                                    .addComponent(strategyPortfolioNumberField)
                                    .addComponent(strategyNumberField)
                                    .addComponent(strategyStartDateField)
                                    .addComponent(strategyEndDateComboBox, 0,
                                            DEFAULT_SIZE,
                                            Short.MAX_VALUE)
                                    .addComponent(strategyEndDateField)
                                    .addComponent(strategyFrequencyField)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(LEADING)
                                                    .addComponent(
                                                            strategyPortfolioNumberLabel)
                                                    .addComponent(strategyNumberLabel)
                                                    .addComponent(startDateLabel)
                                                    .addComponent(strategyEndDateLabel)
                                                    .addComponent(strategyEndDateLbl)
                                                    .addComponent(strategyFrequencyLabel)
                                                    .addComponent(strategyAmountLabel)
                                                    .addComponent(weightsLabel)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.
                                                                    createParallelGroup(
                                                                            LEADING).addGroup(layout
                                                                    .createSequentialGroup().
                                                                    addComponent(
                                                                            tickerComboBox,
                                                                            PREFERRED_SIZE,
                                                                            DEFAULT_SIZE,
                                                                            PREFERRED_SIZE)
                                                                    .addPreferredGap(
                                                                            ComponentPlacement.
                                                                                    RELATED)
                                                                    .addComponent(
                                                                            weightsTextField,
                                                                            PREFERRED_SIZE,
                                                                            130,
                                                                            PREFERRED_SIZE))
                                                                    .addComponent(customWeightsBtn))
                                                            .addPreferredGap(ComponentPlacement.
                                                                    RELATED)
                                                            .addGroup(layout.createParallelGroup(
                                                                    LEADING)
                                                                    .addComponent(equalWeightsBtn)
                                                                    .addComponent(updateWeightsBtn))
                                                    ))
                                            .addGap(0, 319, Short.MAX_VALUE))
                                    .addComponent(saveStrategyBtn,
                                            DEFAULT_SIZE,
                                            DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(resultLbl)
                            .addContainerGap(DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(strategyPortfolioNumberLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyPortfolioNumberField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyNumberLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyNumberField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(startDateLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyStartDateField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyEndDateLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyEndDateComboBox,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyEndDateLbl)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyEndDateField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyFrequencyLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyFrequencyField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyAmountLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(strategyAmountField, PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(weightsLabel)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(Alignment
                                    .BASELINE)
                                    .addComponent(tickerComboBox,
                                            PREFERRED_SIZE,
                                            DEFAULT_SIZE,
                                            PREFERRED_SIZE)
                                    .addComponent(weightsTextField,
                                            PREFERRED_SIZE,
                                            DEFAULT_SIZE,
                                            PREFERRED_SIZE)
                                    .addComponent(updateWeightsBtn))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(Alignment.
                                    BASELINE)
                                    .addComponent(customWeightsBtn)
                                    .addComponent(equalWeightsBtn))
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(saveStrategyBtn)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(resultLbl)
                            .addContainerGap(21, Short.MAX_VALUE))
    );
  } // </editor-fold>//GEN-END:initComponents

  /**
   * Private helper method which is used to fetch the stocks.
   *
   * @param l the event object which listens for a focus change event.
   */
  private void getStocks(FocusEvent l) {
    tickerComboBox.removeAllItems();
    String pNumber = strategyPortfolioNumberField.getText();
    String date = strategyStartDateField.getText();
    try {
      int pn = Integer.parseInt(pNumber);
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      Date date1 = dateFormat.parse(date);
      if (pn < 0) {
        this.resultLbl.setText("Portfolio number cannot be negative");
        return;
      } else if (date1.after(new Date())) {
        this.resultLbl.setText("Future dates are not allowed.");
        return;
      }
      stockList = this.stockMarketController.viewComposition(pn, date);
      for (Stock stock : stockList) {
        tickerComboBox.addItem(stock.getTicker());
      }
    } catch (NumberFormatException ne) {
      resultLbl.setText("Enter a valid portfolio number.");
    } catch (ParseException e) {
      resultLbl.setText("Enter valid date of format (yyyy-MM-dd).");
    }
  }

  /**
   * Private helper method which is used to update weights.
   *
   * @param actionEvent is the event object.
   */
  private void updateWeights(ActionEvent actionEvent) {
    String ticker = (String) tickerComboBox.getSelectedItem();
    String tickerWeight = weightsTextField.getText();
    int tWeight = Integer.parseInt(tickerWeight);
    if (tWeight < 0) {
      resultLbl.setText("Weight cannot be negative");
    } else {
      weights.put(ticker, tWeight);
      resultLbl.setText("Weight updated.");
    }
  }

  /**
   * Private helper method which is used to execute strategy.
   *
   * @param actionEvent is the event object.
   * @param custom      is the flag for custom and equal weights.
   */
  private void executeStrategy(ActionEvent actionEvent, boolean custom) {
    String pNumber = strategyPortfolioNumberField.getText();
    String startDate = strategyStartDateField.getText();
    String investmentAmount = strategyAmountField.getText();
    String frequency = strategyFrequencyField.getText();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String endDate;
    if (strategyEndDateComboBox.getSelectedIndex() == 1) {
      endDate = strategyEndDateField.getText();
    } else {
      endDate = dateFormat.format(new Date());
    }
    double amount;
    try {
      int pn = Integer.parseInt(pNumber);
      int freqNumber = Integer.parseInt(frequency);
      amount = Double.parseDouble(investmentAmount);
      Date sdate = dateFormat.parse(startDate);
      Date edate = dateFormat.parse(endDate);
      if (freqNumber < 0) {
        resultLbl.setText("Frequency cannot be negative.");
        return;
      } else if (sdate.after(edate)) {
        resultLbl.setText("Start date cannot be after end date.");
        return;
      }
      if (custom) {
        if (weights.entrySet().stream().mapToInt(Map.Entry::getValue).sum() != 100) {
          resultLbl.setText("Weights sum must be 100.");
          return;
        }
        String response;
        boolean flag = true;
        for (Map.Entry<String, Integer> entry : weights.entrySet()) {
          double investAmount = (entry.getValue() / 100.0) * amount;
          response = this.stockMarketController.executeStrategy(entry.getKey(),
                  investAmount, startDate, endDate, pn, freqNumber);
          if (!response.trim().equals("pass")) {
            flag = false;
          }
        }
        if (flag) {
          resultLbl.setText("Strategy execution successful.");
        }
      } else {
        String response;
        boolean flag = true;
        for (Map.Entry<String, Integer> entry : weights.entrySet()) {
          double investAmount = (100.0 / weights.size()) * amount;
          response = this.stockMarketController.executeStrategy(entry.getKey(),
                  investAmount, startDate, endDate, pn, freqNumber);
          if (!response.trim().equals("pass")) {
            flag = false;
          }
        }
        if (flag) {
          resultLbl.setText("Strategy execution successful.");
        }
      }
    } catch (NumberFormatException e) {
      resultLbl.setText("Enter a valid number for amount");
    } catch (IllegalArgumentException ie) {
      resultLbl.setText(ie.getMessage());
    } catch (ParseException pe) {
      resultLbl.setText("Enter valid date of format (yyyy-MM-dd).");
    }
  }

  /**
   * Private helper method which is used to save the strategy.
   *
   * @param actionEvent is the event object.
   */
  private void saveStrategy(ActionEvent actionEvent) {
    String strategyNumber = strategyNumberField.getText();
    String startDate = strategyStartDateField.getText();
    String investmentAmount = strategyAmountField.getText();
    String frequency = strategyFrequencyField.getText();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String endDate;
    if (strategyEndDateComboBox.getSelectedIndex() == 1) {
      endDate = strategyEndDateField.getText();
    } else {
      endDate = dateFormat.format(new Date());
    }
    double amount;
    try {
      int sn = Integer.parseInt(strategyNumber);
      int freqNumber = Integer.parseInt(frequency);
      amount = Double.parseDouble(investmentAmount);
      Date sdate = dateFormat.parse(startDate);
      Date edate = dateFormat.parse(endDate);
      if (sn < 0) {
        resultLbl.setText("Strategy number cannot be negative");
        return;
      } else if (freqNumber < 0) {
        resultLbl.setText("Frequency cannot be negative.");
        return;
      } else if (sdate.after(edate)) {
        resultLbl.setText("Start date cannot be after end date.");
        return;
      } else if (amount < 0) {
        resultLbl.setText("Amount cannot be negative");
        return;
      }

      String response = this.stockMarketController.saveStrategy(strategyNumber,
              amount, startDate, endDate, freqNumber);
      if (response.equals("pass")) {
        resultLbl.setText("Strategy saved.");
      }
    } catch (NumberFormatException ne) {
      resultLbl.setText("Enter a valid number.");
    } catch (IllegalArgumentException ie) {
      resultLbl.setText(ie.getMessage());
    } catch (ParseException pe) {
      resultLbl.setText("Enter valid date of format (yyyy-MM-dd).");
    }
  }

  private javax.swing.JLabel resultLbl;
  private javax.swing.JTextField strategyAmountField;
  private javax.swing.JComboBox<String> strategyEndDateComboBox;
  private javax.swing.JTextField strategyEndDateField;
  private javax.swing.JLabel strategyEndDateLbl;
  private javax.swing.JTextField strategyFrequencyField;
  private javax.swing.JTextField strategyPortfolioNumberField;
  private javax.swing.JTextField strategyStartDateField;
  private javax.swing.JComboBox<String> tickerComboBox;
  private javax.swing.JTextField weightsTextField;
  private javax.swing.JTextField strategyNumberField;
  // End of variables declaration//GEN-END:variables
}
