package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaspatwardhan
 */
public class CreatePortfolioPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPortfolioPanel
     */
    public CreatePortfolioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPortfolioLabel = new javax.swing.JLabel();
        createPortfolioTextField = new javax.swing.JTextField();
        createPortfolioBtn = new javax.swing.JButton();

        createPortfolioLabel.setName("createPortfolioLabel");
        createPortfolioTextField.setName("createPortfolioTextField");
        createPortfolioBtn.setName("createPortfolioBtn");

        createPortfolioLabel.setText("Please enter the portfolio number.");

        createPortfolioTextField.setText("Enter number here.");
        createPortfolioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPortfolioTextFieldActionPerformed(evt);
            }
        });

        createPortfolioBtn.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createPortfolioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addComponent(createPortfolioTextField)
                    .addComponent(createPortfolioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createPortfolioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPortfolioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createPortfolioBtn)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createPortfolioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPortfolioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPortfolioTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPortfolioBtn;
    private javax.swing.JLabel createPortfolioLabel;
    private javax.swing.JTextField createPortfolioTextField;
    // End of variables declaration//GEN-END:variables
}
