package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaspatwardhan
 */
public class CreateStrategyPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateStrategypanel
     */
    public CreateStrategyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        strategyPortfolioNumberLabel = new javax.swing.JLabel();
        strategyPortfolioNumberField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        strategyStartDateField = new javax.swing.JTextField();
        strategyEndDateLabel = new javax.swing.JLabel();
        strategyEndDateComboBox = new javax.swing.JComboBox<>();
        strategyEndDateLbl = new javax.swing.JLabel();
        strategyEndDateField = new javax.swing.JTextField();
        strategyFrequencyLabel = new javax.swing.JLabel();
        strategyFrequencyField = new javax.swing.JTextField();
        strategyWeightsLabel = new javax.swing.JLabel();
        strategyWeightsComboBox = new javax.swing.JComboBox<>();
        strategyCustomWeightsLabel = new javax.swing.JLabel();
        strategyCustomWeightsField = new javax.swing.JTextField();
        strategyAmountLabel = new javax.swing.JLabel();
        strategyAmountField = new javax.swing.JTextField();
        strategyInvestBtn = new javax.swing.JButton();

        strategyPortfolioNumberLabel.setText("Please enter the portfolio number.");

        strategyPortfolioNumberField.setText("Enter the portfolio number here.");

        jLabel1.setText("Please enter the start date (yyyy-mm-dd).");

        strategyStartDateField.setText("Enter start date here.");

        strategyEndDateLabel.setText("Would you like to enter the end date.");

        strategyEndDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        strategyEndDateLbl.setText("Please enter the end date.");

        strategyEndDateField.setText("Enter the end date here.");

        strategyFrequencyLabel.setText("Please enter the frequency (in days).");

        strategyFrequencyField.setText("Enter the frequency here.");

        strategyWeightsLabel.setText("Select the weight distribution.");

        strategyWeightsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equal", "Custom" }));

        strategyCustomWeightsLabel.setText("Please enter the custom weights below (weight1, weight2).");

        strategyCustomWeightsField.setText("Enter comma separated weights here.");

        strategyAmountLabel.setText("Please enter the amount you would like to invest ($).");

        strategyAmountField.setText("Enter the amount here.");

        strategyInvestBtn.setText("Create Strategy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(strategyWeightsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(strategyCustomWeightsField)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(strategyAmountLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(strategyAmountField)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strategyPortfolioNumberField)
                    .addComponent(strategyStartDateField)
                    .addComponent(strategyEndDateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(strategyEndDateField)
                    .addComponent(strategyFrequencyField)
                    .addComponent(strategyInvestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strategyPortfolioNumberLabel)
                            .addComponent(jLabel1)
                            .addComponent(strategyEndDateLabel)
                            .addComponent(strategyEndDateLbl)
                            .addComponent(strategyFrequencyLabel)
                            .addComponent(strategyWeightsLabel)
                            .addComponent(strategyCustomWeightsLabel))
                        .addGap(0, 395, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(strategyPortfolioNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyPortfolioNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyEndDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyEndDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyEndDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyFrequencyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyFrequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyWeightsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyWeightsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyCustomWeightsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyCustomWeightsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strategyInvestBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField strategyAmountField;
    private javax.swing.JLabel strategyAmountLabel;
    private javax.swing.JTextField strategyCustomWeightsField;
    private javax.swing.JLabel strategyCustomWeightsLabel;
    private javax.swing.JComboBox<String> strategyEndDateComboBox;
    private javax.swing.JTextField strategyEndDateField;
    private javax.swing.JLabel strategyEndDateLabel;
    private javax.swing.JLabel strategyEndDateLbl;
    private javax.swing.JTextField strategyFrequencyField;
    private javax.swing.JLabel strategyFrequencyLabel;
    private javax.swing.JButton strategyInvestBtn;
    private javax.swing.JTextField strategyPortfolioNumberField;
    private javax.swing.JLabel strategyPortfolioNumberLabel;
    private javax.swing.JTextField strategyStartDateField;
    private javax.swing.JComboBox<String> strategyWeightsComboBox;
    private javax.swing.JLabel strategyWeightsLabel;
    // End of variables declaration//GEN-END:variables
}
