package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import controller.IStockMarketController;

/**
 * The class Graph panel.
 *
 * @author ojaspatwardhan
 */
public class GraphPanel extends javax.swing.JPanel {

  private IStockMarketController stockMarketController;

  /**
   * Creates new form GraphPanel.
   *
   * @param stockMarketController the stock market controller
   */
  public GraphPanel(IStockMarketController stockMarketController) {
    initComponents();
    this.stockMarketController = stockMarketController;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.JLabel portfolioNumberLbl = new javax.swing.JLabel();
    portfolioNumberTextField = new javax.swing.JTextField();
    javax.swing.JButton plotGraphBtn = new javax.swing.JButton();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel dateLbl = new javax.swing.JLabel();
    dateTextField = new javax.swing.JTextField();

    portfolioNumberLbl.setText("Enter portfolio number.");

    portfolioNumberTextField.setText("Enter number here");

    plotGraphBtn.setText("Plot");
    plotGraphBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        plotGraphBtnActionPerformed(evt);
      }
    });

    dateLbl.setText("Enter start date (yyyy-mm-dd)");

    dateTextField.setText("Enter date");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portfolioNumberTextField)
                    .addComponent(dateTextField)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment
                                    .LEADING)
                                    .addComponent(portfolioNumberLbl)
                                    .addComponent(dateLbl))
                            .addContainerGap(1096, Short.MAX_VALUE))
                    .addComponent(plotGraphBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(portfolioNumberLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(portfolioNumberTextField, javax.swing.GroupLayout
                                            .PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.
                                            PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.
                                            PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(plotGraphBtn)
                            .addContainerGap(656, Short.MAX_VALUE))
    );
  } // </editor-fold>//GEN-END:initComponents

  private void plotGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {
    //GEN-FIRST:event_plotGraphBtnActionPerformed
    // TODO add your handling code here:
    new SampleGraphFrame(portfolioNumberTextField.getText(), "Portfolio Graph",
            "Portfolio Graph Chart", dateTextField.getText(),
            this.stockMarketController);
  } //GEN-LAST:event_plotGraphBtnActionPerformed


  private javax.swing.JTextField dateTextField;
  private javax.swing.JTextField portfolioNumberTextField;
  // End of variables declaration//GEN-END:variables
}
