package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ojaspatwardhan
 */
public class InvestPanel extends javax.swing.JPanel {

    /**
     * Creates new form InvestPanel
     */
    public InvestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        investPortfolioNumberLabel = new javax.swing.JLabel();
        investPortfolioField = new javax.swing.JTextField();
        investDateLabel = new javax.swing.JLabel();
        investDateField = new javax.swing.JTextField();
        investWeightsLabel = new javax.swing.JLabel();
        investWeightsComboBox = new javax.swing.JComboBox<>();
        amountToInvestLabel = new javax.swing.JLabel();
        amountToinvesttextField = new javax.swing.JTextField();
        investBtn = new javax.swing.JButton();

        investPortfolioNumberLabel.setText("Please enter the portfolio number.");

        investPortfolioField.setText("Enter the portfolio number here.");

        investDateLabel.setText("Please enter the date (yyyy-mm-dd).");

        investDateField.setText("Enter date here.");

        investWeightsLabel.setText("Please select the weight distribution.");

        investWeightsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equal Weights", "Custom Weights" }));

        amountToInvestLabel.setText("Please enter the amount you would like to invest.");

        amountToinvesttextField.setText("Enter amount here.");

        investBtn.setText("Invest");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(investBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(investWeightsComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(investPortfolioField)
                            .addComponent(investDateField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(investPortfolioNumberLabel)
                                    .addComponent(investDateLabel)
                                    .addComponent(investWeightsLabel)
                                    .addComponent(amountToInvestLabel))
                                .addGap(0, 78, Short.MAX_VALUE))))
                    .addComponent(amountToinvesttextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(investPortfolioNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investPortfolioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(investWeightsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(investWeightsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountToInvestLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountToinvesttextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(investBtn)
                .addGap(0, 42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountToInvestLabel;
    private javax.swing.JTextField amountToinvesttextField;
    private javax.swing.JButton investBtn;
    private javax.swing.JTextField investDateField;
    private javax.swing.JLabel investDateLabel;
    private javax.swing.JTextField investPortfolioField;
    private javax.swing.JLabel investPortfolioNumberLabel;
    private javax.swing.JComboBox<String> investWeightsComboBox;
    private javax.swing.JLabel investWeightsLabel;
    // End of variables declaration//GEN-END:variables
}
