package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.GroupLayout.Alignment;

import controller.IStockMarketController;
import model.Stock;

import static javax.swing.GroupLayout.DEFAULT_SIZE;
import static javax.swing.GroupLayout.PREFERRED_SIZE;


/**
 * The class Invest panel.
 *
 * @author ojaspatwardhan
 */
public class InvestPanel extends javax.swing.JPanel {

  private List<Stock> stockList;
  private Map<String, Integer> weights;
  private IStockMarketController stockMarketController;

  /**
   * Creates new form InvestPanel.
   *
   * @param stockMarketController the stock market controller
   */
  public InvestPanel(IStockMarketController stockMarketController) {
    initComponents();
    this.stockMarketController = stockMarketController;
    stockList = new ArrayList<>();
    weights = new HashMap<>();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    javax.swing.JLabel investPortfolioNumberLbl = new javax.swing.JLabel();
    investPortfolioField = new javax.swing.JTextField();
    javax.swing.JLabel investDateLabel = new javax.swing.JLabel();
    investDateField = new javax.swing.JTextField();
    // Variables declaration - do not modify
    javax.swing.JLabel amountToInvestLabel = new javax.swing.JLabel();
    amountToinvesttextField = new javax.swing.JTextField();
    javax.swing.JButton investBtn = new javax.swing.JButton();
    javax.swing.JLabel wL = new javax.swing.JLabel();
    tickersComboBox = new javax.swing.JComboBox<>();
    weightsTextField = new javax.swing.JTextField();
    javax.swing.JButton customWeightsBtn = new javax.swing.JButton();
    javax.swing.JButton equalWeightsBtn = new javax.swing.JButton();
    javax.swing.JButton updateWeightsBtn = new javax.swing.JButton();
    resultLabel = new javax.swing.JLabel();

    investPortfolioNumberLbl.setText("Please enter the portfolio number.");

    investPortfolioField.setText("");

    investDateLabel.setText("Please enter the date (yyyy-mm-dd).");

    investDateField.setText("");

    amountToInvestLabel.setText("Please enter the amount you would like to invest.");

    amountToinvesttextField.setText("");

    investBtn.setText("Invest");

    wL.setText("Select Ticker.");

    tickersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>());

    weightsTextField.setText("Enter weight");

    customWeightsBtn.setText("Execute with custom weights");

    equalWeightsBtn.setText("Execute using equal weights");

    updateWeightsBtn.setText("Update Weight");

    investDateField.addFocusListener(new FocusListener() {
      @Override
      public void focusGained(FocusEvent focusEvent) {
        //do nothing.
      }

      @Override
      public void focusLost(FocusEvent focusEvent) {
        getStocks(focusEvent);
      }
    });

    updateWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        updateWeights(actionEvent);
      }
    });

    customWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        invest(actionEvent, true);
      }
    });

    equalWeightsBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        invest(actionEvent, false);
      }
    });

    tickersComboBox.addFocusListener(new FocusListener() {
      @Override
      public void focusGained(FocusEvent focusEvent) {
        resultLabel.setText("");
      }

      @Override
      public void focusLost(FocusEvent focusEvent) {
        //do nothing.
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(
                                    Alignment.LEADING)
                                    .addComponent(investBtn,
                                            DEFAULT_SIZE,
                                            DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(
                                                    Alignment.LEADING)
                                                    .addComponent(investPortfolioField)
                                                    .addComponent(investDateField)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(
                                                                    Alignment.LEADING)
                                                                    .addComponent(
                                                                            investPortfolioNumberLbl
                                                                    )
                                                                    .addComponent(investDateLabel)
                                                                    .addComponent(
                                                                            amountToInvestLabel)
                                                                    .addComponent(resultLabel))
                                                            .addGap(0, 416,
                                                                    Short.MAX_VALUE))
                                                    .addComponent(amountToinvesttextField)))
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(
                                                    Alignment.TRAILING,
                                                    false)
                                                    .addComponent(customWeightsBtn,
                                                            Alignment.
                                                                    LEADING,
                                                            DEFAULT_SIZE,
                                                            251, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(
                                                                    Alignment.TRAILING,
                                                                    false)
                                                                    .addComponent(tickersComboBox,
                                                                            Alignment.
                                                                                    LEADING,
                                                                            0,
                                                                            DEFAULT_SIZE,
                                                                            Short.MAX_VALUE)
                                                                    .addGroup(Alignment.LEADING,
                                                                    layout.createSequentialGroup().
                                                                                    addContainerGap(

                                                                                    )
                                                                                    .addComponent(wL
                                                                                    )))
                                                                    .addPreferredGap(
                                                                    javax.swing.LayoutStyle.
                                                                            ComponentPlacement.
                                                                            RELATED)
                                                            .addComponent(weightsTextField,
                                                                    PREFERRED_SIZE,
                                                                    145, PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(
                                                    Alignment.LEADING)
                                                    .addComponent(equalWeightsBtn,
                                                            PREFERRED_SIZE,
                                                            247, PREFERRED_SIZE)
                                                    .addComponent(updateWeightsBtn))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(investPortfolioNumberLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(investPortfolioField, PREFERRED_SIZE, DEFAULT_SIZE, 
                                    PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(investDateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(investDateField, PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(amountToInvestLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(amountToinvesttextField,
                                    PREFERRED_SIZE,
                                    DEFAULT_SIZE,
                                    PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(wL)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(
                                    Alignment.BASELINE)
                                    .addComponent(tickersComboBox,
                                            PREFERRED_SIZE,
                                            DEFAULT_SIZE,
                                            PREFERRED_SIZE)
                                    .addComponent(weightsTextField,
                                            PREFERRED_SIZE,
                                            DEFAULT_SIZE,
                                            PREFERRED_SIZE)
                                    .addComponent(updateWeightsBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(
                                    Alignment.BASELINE)
                                    .addComponent(customWeightsBtn)
                                    .addComponent(equalWeightsBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    140, Short.MAX_VALUE)
                            .addComponent(resultLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                    140, Short.MAX_VALUE)
                            .addComponent(investBtn)
                            .addContainerGap())
    );
  } // </editor-fold>

  /**
   * Private helper method to get stocks.
   *
   * @param l is the event object.
   */
  private void getStocks(FocusEvent l) {
    tickersComboBox.removeAllItems();
    String pNumber = investPortfolioField.getText();
    String date = investDateField.getText();
    try {
      int pn = Integer.parseInt(pNumber);
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      Date date1 = dateFormat.parse(date);
      if (pn < 0) {
        this.resultLabel.setText("Portfolio number cannot be negative");
        return;
      } else if (date1.after(new Date())) {
        this.resultLabel.setText("Future dates are not allowed.");
        return;
      }
      stockList = this.stockMarketController.viewComposition(pn, date);
      for (Stock stock : stockList) {
        tickersComboBox.addItem(stock.getTicker());
      }
    } catch (NumberFormatException ne) {
      resultLabel.setText("Enter a valid portfolio number.");
    } catch (ParseException e) {
      resultLabel.setText("Enter valid date of format (yyyy-MM-dd).");
    }
  }

  /**
   * Private helper method used to update weights.
   *
   * @param actionEvent is the event object.
   */
  private void updateWeights(ActionEvent actionEvent) {
    resultLabel.setText("");
    String ticker = (String) tickersComboBox.getSelectedItem();
    String tickerWeight = weightsTextField.getText();
    int tWeight = Integer.parseInt(tickerWeight);
    if (tWeight < 0) {
      resultLabel.setText("Weight cannot be negative");
    } else {
      weights.put(ticker, tWeight);
      resultLabel.setText("Weight updated.");
    }
  }

  /**
   * Private helper method to invest.
   *
   * @param actionEvent is the event object.
   * @param custom      is the flag for equal and custom weights.
   */
  private void invest(ActionEvent actionEvent, boolean custom) {
    String pNumber = investPortfolioField.getText();
    String date = investDateField.getText();
    String investmentAmount = amountToinvesttextField.getText();
    int pn;
    double amount;
    try {
      pn = Integer.parseInt(pNumber);
      amount = Double.parseDouble(investmentAmount);
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      Date date1 = dateFormat.parse(date);
      if (custom) {
        if (weights.entrySet().stream().mapToInt(Map.Entry::getValue).sum() != 100) {
          resultLabel.setText("Weights sum must be 100.");
          return;
        }
        String response;
        boolean flag = true;
        for (Map.Entry<String, Integer> entry : weights.entrySet()) {
          double investAmount = (entry.getValue() / 100.0) * amount;
          response = this.stockMarketController.buyStockByAmount(entry.getKey(),
                  investAmount, date, pn, 0);
          if (!response.trim().equals("pass")) {
            flag = false;
          }
        }
        if (flag) {
          resultLabel.setText("Investment successful.");
        }
      } else {
        String response;
        boolean flag = true;
        for (Map.Entry<String, Integer> entry : weights.entrySet()) {
          double investAmount = (100.0 / weights.size()) * amount;
          response = this.stockMarketController.buyStockByAmount(entry.getKey(), investAmount,
                  date, pn, 0);
          if (!response.trim().equals("pass")) {
            flag = false;
          }
        }
        if (flag) {
          resultLabel.setText("Investment successful.");
        }
      }
    } catch (NumberFormatException e) {
      resultLabel.setText("Enter a valid number for amount");
    } catch (IllegalArgumentException ie) {
      resultLabel.setText(ie.getMessage());
    } catch (ParseException pe) {
      resultLabel.setText("Enter valid date of format (yyyy-MM-dd).");
    }
  }


  private javax.swing.JTextField amountToinvesttextField;
  private javax.swing.JTextField investDateField;
  private javax.swing.JTextField investPortfolioField;
  private javax.swing.JComboBox<String> tickersComboBox;
  private javax.swing.JTextField weightsTextField;
  private javax.swing.JLabel resultLabel;
  // End of variables declaration
}