package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import controller.IStockMarketController;

/**
 * The class Save portfolio panel.
 *
 * @author ojaspatwardhan
 */
public class SavePortfolioPanel extends javax.swing.JPanel {

  private IStockMarketController stockMarketController;

  /**
   * Creates new form SavePortfolioPanel.
   *
   * @param stockMarketController the stock market controller
   */
  public SavePortfolioPanel(IStockMarketController stockMarketController) {
    initComponents();
    this.stockMarketController = stockMarketController;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel portfolioNumberLbl = new javax.swing.JLabel();
    portfolioNumberTextField = new javax.swing.JTextField();
    javax.swing.JButton savePortfolioBtn = new javax.swing.JButton();
    resultLabel = new javax.swing.JLabel();

    portfolioNumberLbl.setText("Enter portfolio number.");

    savePortfolioBtn.setText("Save Portfolio");

    savePortfolioBtn.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent actionEvent) {
        savePortfolio(actionEvent);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savePortfolioBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(portfolioNumberTextField)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(portfolioNumberLbl)
                                            .addComponent(resultLabel)
                                            .addGap(0, 1055, Short.MAX_VALUE)))
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(portfolioNumberLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(portfolioNumberTextField,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(savePortfolioBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(resultLabel)
                            .addContainerGap(715, Short.MAX_VALUE))
    );
  } // </editor-fold>//GEN-END:initComponents

  /**
   * Private method used to save a portfolio.
   *
   * @param actionEvent is the event object.
   */
  private void savePortfolio(ActionEvent actionEvent) {
    String pNumber = portfolioNumberTextField.getText();
    try {
      int pn = Integer.parseInt(pNumber);
      if (pn < 0) {
        resultLabel.setText("Enter positive number.");
      } else {
        String response = this.stockMarketController.savePortfolio(pn);
        if (response.equals("pass")) {
          resultLabel.setText("Save portfolio successful");
        }
      }
    } catch (NumberFormatException ne) {
      resultLabel.setText("Enter a number.");
    } catch (IllegalArgumentException ie) {
      resultLabel.setText(ie.getMessage());
    }
  }

  private javax.swing.JTextField portfolioNumberTextField;
  private javax.swing.JLabel resultLabel;
  // End of variables declaration//GEN-END:variables
}
