package view;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;
import java.io.IOException;
import java.util.List;

import javax.swing.*;

import controller.IStockMarketController;

/**
 * The type Welcome frame.
 *
 * @author ojaspatwardhan
 */
public class WelcomeFrame extends JFrame implements IStockMarketView {

  private CreatePortfolioPanel createPortfolioPanel;

  /**
   * Creates new form WelcomeFrame
   */
  public WelcomeFrame() {
        initComponents();
        createPortfolioPanel = new CreatePortfolioPanel();
    }

  @Override
  public String enterCommand() throws IOException {
    return null;
  }

  @Override
  public void result(String result) throws IOException {

  }

  @Override
  public String continueTakingWeights(List<String> stockList) throws IOException {
    return null;
  }

  @Override
  public String getEqualWeightsAmount() throws IOException {
    return null;
  }

  @Override
    public void setFeatures(IStockMarketController c) {
    createPortfolioButton.addActionListener(l -> createPortfolio(c));
    /*buyStockButton
    investButton
    viewCompositionButton
    exitButton
    createStrategyButton
    costbasisEvaluationButton*/
    }

  /**
   * Private helper method to set the component inside the view.
   * @param c is the controller object.
   */
  private void createPortfolio(IStockMarketController c) {
    jSplitPane1.setRightComponent(createPortfolioPanel);
    loadCreatePortfolioComponents(c);
    }

  /**
   * Helper method to load components of create portfolio panel.
   * @param c is the controller object.
   */
  private void loadCreatePortfolioComponents(IStockMarketController c) {
    Component inputTextFieldComponent = null;
    Component createPortfolioBtnComponent = null;
    Component createPortfolioLblComponent = null;
    JTextField inputTextField;
    JButton createPortfolioBtn;
    JLabel createPortfolioLbl;
    Component[] components = createPortfolioPanel.getComponents();
    for (Component component : components) {
      if (component.getName() != null && component.getName().equals("createPortfolioTextField")) {
        inputTextFieldComponent = component;
      } else if (component.getName() != null && component.getName().equals("createPortfolioBtn")) {
        createPortfolioBtnComponent = component;
      } else if (component.getName() != null
              && component.getName().equals("createPortfolioLabel")) {
        createPortfolioLblComponent = component;
      }
    }

    inputTextField = (JTextField) inputTextFieldComponent;
    createPortfolioBtn = (JButton) createPortfolioBtnComponent;
    createPortfolioLbl = (JLabel) createPortfolioLblComponent;

    createPortfolioBtn.addActionListener(l -> c.createPortfolio(inputTextField.getText()));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

      jSplitPane1 = new javax.swing.JSplitPane();
      jPanel1 = new javax.swing.JPanel();
      createPortfolioButton = new javax.swing.JButton();
      buyStockButton = new javax.swing.JButton();
      investButton = new javax.swing.JButton();
      viewCompositionButton = new javax.swing.JButton();
      exitButton = new javax.swing.JButton();
      createStrategyButton = new javax.swing.JButton();
      costbasisEvaluationButton = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      createPortfolioButton.setText("Create");

      buyStockButton.setText("Buy Stock");

      investButton.setText("Invest");

      viewCompositionButton.setText("Composition");

      exitButton.setText("Exit");

      createStrategyButton.setText("Create Strategy");

      costbasisEvaluationButton.setText("Cost Basis & Evaluation");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
          jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(investButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(createPortfolioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(buyStockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(createStrategyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
              .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addContainerGap())
          .addComponent(costbasisEvaluationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(viewCompositionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
          jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
              .addContainerGap()
              .addComponent(createPortfolioButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(buyStockButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(investButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(createStrategyButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(viewCompositionButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(costbasisEvaluationButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(exitButton)
              .addContainerGap(51, Short.MAX_VALUE))
      );

      jSplitPane1.setLeftComponent(jPanel1);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 196, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
          jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGap(0, 296, Short.MAX_VALUE)
      );

      jSplitPane1.setRightComponent(jPanel2);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSplitPane1)
      );
      layout.setVerticalGroup(
          layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jSplitPane1)
      );

      pack();
      setVisible(true);
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Main.
   *
   * @param args the command line arguments
   */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyStockButton;
    private javax.swing.JButton costbasisEvaluationButton;
    private javax.swing.JButton createPortfolioButton;
    private javax.swing.JButton createStrategyButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton investButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton viewCompositionButton;
    // End of variables declaration//GEN-END:variables
}
